version: '3.9'

services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile.webserver
        image: hqrental/webserver
        ports:
            - "${APP_PORT:-8080}:80"
        volumes:
            - ${PWD}/public:/var/www/public
        depends_on:
            - runtime
        networks:
            - hqrental
        environment:
            NGINX_RUNTIME_HOST: ${NGINX_RUNTIME_HOST:-runtime}

    runtime:
        build:
            context: .
            dockerfile: Dockerfile.runtime
            target: ${RUNTIME_BUILD_TARGET:-local}
        image: hqrental/runtime
        ports:
            - "9000"
        volumes:
            - ${PWD}/:/var/www
        depends_on:
            - database
        networks:
            - hqrental

    database:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - hqrental
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    test_database:
        image: 'mysql/mysql-server:8.0'
        tmpfs:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

        networks:
            - hqrental

networks:
    hqrental:
        driver: bridge
